.\" Process this file with
.\" groff -man -Tascii boj.1
.\"
.ds @@VERSION 0.6.1
.ds @@AUTHOR Paul Hoffman <paul@flo.org>
.ds @@COPYRIGHT Copyright 2012 Fenway Libraries Online.
.
.TH BOJ 1 "boj"
.
.
.SH NAME
.
boj \- run a batch job and mail output
.
.
.\" -----------------------------------------------------------------
.
.SH SYNOPSIS
.
.B boj
[
.IR OPTION .\|.\|.\&
]
.I COMMAND
[
.IR ARG .\|.\|.\&
]
.
.\" -----------------------------------------------------------------
.
.SH DESCRIPTION
.
.B boj
runs
.I COMMAND
for a user and mails its output (if any) to the user.
.
.\" -----------------------------------------------------------------
.
.SH OPTIONS
.
.TP
.B -n
Don't send mail unless
.I COMMAND
exited with non-zero status.
.
.TP
.B -m
Always send mail, regardless of whether
.I COMMAND
exited with non-zero status or produced any output.
.
.TP
.B -k
Keep the output file.
.
.TP
.B -r
Remove the output file before exiting.
.
.TP
.B -e
Include a banner listing environment variables and their values at the top of
any output that is sent via mail.
.
.TP
.BI -d " DIR"
Change to
.I DIR
before running the job.
.
.TP
.BI -o " FILE"
Put output in
.I FILE
rather than a temporary file in
.B /tmp
-- this implies option
.B -k
which can be overridden by option
.BR -r .
.
.TP
.BI -l " FILE"
Log the result in
.I FILE
rather than
.BR /var/log/boj.log .
The log entry consists of the result code
.B OK
or
.B FAIL
followed by the time execution began, the time it ended,
and finally
.I COMMAND
along with its arguments.
.
.TP
.B -L
Log the result in
.BR ~/.bojlog .
This is the default if
.B /var/log/boj.log
is not writeable.
.
.TP
.BI -f " ADDRESS"
Use
.I ADDRESS
as the sender of the notification.
.
.TP
.BI -t " ADDRESS"
Send the notification to
.IR ADDRESS .
.
.TP
.BI -s " STRING"
Use
.I STRING
as the subject of the notification.  The default subject is
.B [$H]: [$r] $c
(see
.B OUTPUT
below for a key to the embedded variables).
.
.TP
.BI -p " DIR"
Use
.I DIR
as the
.BR "project directory" .
(see below).
.
.\" -----------------------------------------------------------------
.
.SH PROJECTS
.
The
.B -p
option sets the following options:
.
.TP
.B -d
.I DIR
.
.TP
.B -o
out
.
.TP
.B -l
boj.log
.
.P
It runs the executable at
.IR DIR /run
and sends a notification using the mail template in the first of the
following files that it finds in the project directory:
.
.TP
.BI mail. err
.TP
.BI mail. result
.TP
.B mail
.
.P
Here,
.I err
is the exist status of the executable and
.I result
is either
.B OK
or
.B FAIL
depending on whether the exit status was zero or not.
.P
These files must contain a complete and valid mail header followed by a blank
line; optional lines that follow the blank line will become part of the message
body.
.P
If none of these files is found, a sensible default is used.
.
.P
To invoke the executable at
.IR DIR /run
with arguments, add them after the last option.
.P
To run an executable other than the file
.B run
in the project directory, add brackets around the executable name (or path) and
its arguments.  For example:
.
.P
.B boj -p
.I DIR
.B [
.I CMD ARG...
.B ]
.P
The brackets here are literals; they do not indicate optional arguments to
.BR boj .
They must occur as separate tokens (i.e., surrounded by whitespace) in order to
be recognized by
.BR boj .
.
If you omit the closing right bracket,
.B ./run
will be added as an additional option.  For example:
.
.P
.B boj -p
.I DIR
.B [ timeout 30
.P
will invoke
.P
.B timeout 30 ./run
.P
from within
.IR dir .
.P
Options
.BR -f ,
.BR -t ,
and
.B -s
are ignored unless a mail template could not be found.
.
.P
Each of the files
.BR keepout ,
.BR alwaysmail ,
.BR nomail ,
and
.BR showenv ,
if it exists, sets the corresponding option.
.
.\" -----------------------------------------------------------------
.
.SH OUTPUT
The following variables are expanded in the header of a message:
.
.TP
.B $R
is replaced by the exit status of the executable.
.
.TP
.B $r
is replaced by
.B OK
or
.B FAIL
depending on whether the exit status of the executable was 0 or not.
.
.TP
.B $4r
is like
.B $r
but padded with spaces on the right so that it always four bytes long.
(This is the only time when a number may be specified.)
.
.TP
.B $c
is replaced by the command (and any arguments).
.
.TP
.B $J
is replaced by
.I DIR
if
.BI -p " DIR"
was specified.
.
.TP
.B $j
is replaced by the trailing component of
.I DIR
if
.BI -p " DIR"
was specified.
.
.TP
.B $u
is replaced by the user name.
.
.TP
.B $h
is replaced by the host name up to the first `.'.
.
.TP
.B $H
is replaced by the full host name.
.\" -----------------------------------------------------------------
.
.\" .SH DIAGNOSTICS
.SH VERSION 
.\" @VERSION 0.6.0
\*[@@VERSION]
.
.SH AUTHOR
.\" @AUTHOR Paul Hoffman <paul@flo.org>
\*[@@AUTHOR]
.
.SH COPYRIGHT
.\" @COPYRIGHT Copyright 2012 Fenway Libraries Online.
\*[@@COPYRIGHT]
.P
Released under the terms of the GNU
General Public License, version 2 -- see the file LICENSE for details.
.
.\" .SH "SEE ALSO"
.\" .BR bar (1),

